events {
    worker_connections 1024;
}

http {
    # Include default MIME types so .html files render correctly in the browser
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 4000;

        # locations are matched in order

        # Static map visualizer
        location /map/ {
            alias /usr/share/nginx/html/map/;
            index index.html;
        }

        # Anything starting with /tracking/ goes to the Tracking Service
        # (calls from the outside, like from ACME and Vehicles)
        location /tracking/position/ {
            proxy_pass http://fleet-tracking:5003/position/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /tracking/battery/ {
            proxy_pass http://fleet-battery:5002/battery/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Generical tracking is also managed by the position service
        location /tracking/ {
            proxy_pass http://fleet-tracking:5003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}