events {
    worker_connections 1024;
}

http {
    server {
        listen 4000;

        # locations are matched in order

        # Anything starting with /tracking/ goes to the Tracking Service
        # (calls from the outside, like from ACME and Vehicles)
        location /tracking/position/ {
            proxy_pass http://fleet-tracking:5003/position/;
            proxy_set_header Host ;
            proxy_set_header X-Real-IP ;
        }

        location /tracking/battery/ {
            proxy_pass http://fleet-battery:5002/battery/;
            proxy_set_header Host ;
            proxy_set_header X-Real-IP ;
        }

        # Generical tracking is also managed by the position service
        location /tracking/ {
            proxy_pass http://fleet-battery:5002;
            proxy_set_header Host ;
            proxy_set_header X-Real-IP ;
        }

    }
}