from util import get_env_or_exit






class EnvConfig:

	# Read Configuration from Docker Environment
	URL_CAMUNDA         = get_env_or_exit('URL_CAMUNDA')
	URL_BANK_WSDL       = get_env_or_exit('URL_BANK_WSDL')
	URL_STATION_BASE    = get_env_or_exit('URL_STATION')
	URL_FLEET_BASE      = get_env_or_exit('URL_FLEET')
	URL_BANK_BASE		= get_env_or_exit('URL_BANK')
	URL_STATION_BASE	= get_env_or_exit('URL_STATION')

	EP_BANK_PREAUTH			= get_env_or_exit('ENDPOINT_BANK_PREAUTH')
	EP_BANK_CHARGE			= get_env_or_exit('ENDPOINT_BANK_CHARGE')
	EP_BANK_UNLOCK_CAUTION	= get_env_or_exit('ENDPOINT_BANK_UNLOCK_CAUTION')

	BANK_CAUTION        = int(get_env_or_exit('BANK_CAUTION'))

	CAMUNDA_USER_ID					= get_env_or_exit('CAMUNDA_VAR_USER_ID')
	CAMUNDA_VEHICLE_ID				= get_env_or_exit('CAMUNDA_VAR_VEHICLE_ID')
	CAMUNDA_IS_IMMEDIATE			= get_env_or_exit('CAMUNDA_VAR_IS_IMMEDIATE')
	CAMUNDA_RESERVE_TIME			= get_env_or_exit('CAMUNDA_VAR_RESERVE_TIME')
	CAMUNDA_BANK_TOKEN				= get_env_or_exit('CAMUNDA_VAR_BANK_TOKEN')
	CAMUNDA_AMOUNT_TO_CHARGE		= get_env_or_exit('CAMUNDA_VAR_AMOUNT_TO_CHARGE')
	CAMUNDA_CONVERT_CAUTION_STATUS	= get_env_or_exit('CAMUNDA_VAR_CONVERT_CAUTION_STATUS')
	CAMUNDA_CAUTION_BLOCKED			= get_env_or_exit('CAMUNDA_VAR_CAUTION_BLOCKED')
	CAMUNDA_PAYMENT_STATUS			= get_env_or_exit('CAMUNDA_VAR_PAYMENT_STATUS')
	CAMUNDA_BATTERY_LEVEL			= get_env_or_exit('CAMUNDA_VAR_BATTERY_LEVEL')
	CAMUNDA_VEHICLE_UNLOCKED		= get_env_or_exit('CAMUNDA_VAR_VEHICLE_UNLOCKED')
	CAMUNDA_CANCEL_MINUTES			= get_env_or_exit('CAMUNDA_VAR_CANCEL_MINUTES')
	CAMUNDA_AMOUNT_BASE				= get_env_or_exit('CAMUNDA_VAR_AMOUNT_BASE')
	CAMUNDA_PENALTY_APPLIED			= get_env_or_exit('CAMUNDA_VAR_PENALTY_APPLIED')

	TOPIC_BANK_PREAUTH				= get_env_or_exit('TOPIC_BANK_PREAUTH')
	TOPIC_BANK_CHARGE				= get_env_or_exit('TOPIC_BANK_CHARGE')
	TOPIC_BANK_CONVERT_CAUTION		= get_env_or_exit('TOPIC_BANK_CONVERT_CAUTION')
	TOPIC_BANK_UNLOCK_CAUTION		= get_env_or_exit('TOPIC_BANK_UNLOCK_CAUTION')
	TOPIC_STATION_LOCK				= get_env_or_exit('TOPIC_STATION_LOCK')
	TOPIC_STATION_UNLOCK			= get_env_or_exit('TOPIC_STATION_UNLOCK')
	TOPIC_FLEET_TRACK_INFO			= get_env_or_exit('TOPIC_FLEET_TRACK_INFO')
	TOPIC_FLEET_TRACK_START			= get_env_or_exit('TOPIC_FLEET_TRACK_START')
	TOPIC_FLEET_TRACK_STOP			= get_env_or_exit('TOPIC_FLEET_TRACK_STOP')
	TOPIC_FLEET_FETCH_BATTERY		= get_env_or_exit('TOPIC_FLEET_FETCH_BATTERY')
	TOPIC_ACME_APPLY_PENALTY		= get_env_or_exit('TOPIC_ACME_APPLY_PENALTY')
	TOPIC_ACME_CALCULATE_CHARGE		= get_env_or_exit('TOPIC_ACME_CALCULATE_CHARGE')
	TOPIC_ACME_CANCELLATION_DELAY	= get_env_or_exit('TOPIC_ACME_CANCELLATION_DELAY')
	TOPIC_ACME_NOTIFY_REJECTION		= get_env_or_exit('TOPIC_ACME_NOTIFY_REJECTION')
	TOPIC_ACME_RESERVE				= get_env_or_exit('TOPIC_ACME_RESERVE')


envConfig = EnvConfig()
