services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: acme-camunda
    ports:
      - "${CAMUNDA_PORT}:8080"
    volumes:
      # Here you map the folder where you save your .bpmn files
      - ./camunda-resources/:/camunda/configuration/resources
    environment:
      - CAMUNDA_BPM_RUN_AUTH_ENABLED=false # disable login for convenience in dev
      #- CAMUNDA_BPM_GENERIC_PROPERTIES_GENERAL_ENFORCE-HISTORY-TIME-TO-LIVE=false
      #- enforceHistoryTimeToLive=false
      # disable example demo invoice app
      - CAMUNDA_BPM_RUN_EXAMPLE_INVOICE_ENABLED=false
      - CAMUNDA_BPM_RUN_WELCOME_APP_ENABLED=false
    networks:
      - acme-network

# fleet:
#   build: ./service-fleet-management
#   networks:
#     - acme-network

#  bank:
#    build: ./service-bank

  config-loader:
    build: ./service-config-loader
    container_name: acme-config-loader
    environment:
      - URL_CAMUNDA=http://camunda:8080/engine-rest
      - URL_BANK=http://bank-service:8000
      - URL_STATION=http://stations-service:5000
      - BANK_CAUTION=10
    depends_on:
      - camunda
    networks:
      - acme-network


networks:
  acme-network:
    driver: bridge