services:
  camunda:
    build: ./camunda
    container_name: acme-camunda
    ports:
      - "${PORT_CAMUNDA}:8080"
    volumes:
      # Here you map the folder where you save your .bpmn files
      - ./camunda-resources/:/camunda/configuration/resources
    networks:
      - orchestration-network

  bank-service:
    build: ./service-bank
    networks:
      - bank-network

  acme-worker:
    build: ./service-acme-worker
    container_name: acme-worker
    env_file:
      - .env
    depends_on:
      - camunda
    networks:
      - acme-network
      - bank-network
      - orchestration-network

# fleet:
#   build: ./service-fleet-management
#   networks:
#     - acme-network

# 5-10 stations


networks:
  acme-network:
    driver: bridge
  bank-network:
    driver: bridge
  fleet-internal-network:
    driver: bridge
  orchestration-network:
    driver: bridge
